# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [master, develop, feature/**]
  pull_request:
    branches: [develop]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "eslint"
  eslint:
    name: eslint
    runs-on: ubuntu-latest
    needs: build
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: Yarn install
        run: yarn install

      - name: Run Eslint
        run: yarn lint

  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
      - name: Yarn install
        run: yarn install

      - name: build
        run: yarn build

  jest:
    name: jest
    runs-on: ubuntu-latest
    needs: eslint
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: Yarn install
        run: yarn install

      - name: Run Jest Coverage
        run: yarn test:coverage

      - name: Upload test coverage artifact
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: coverage

  storybook:
    name: storybook
    runs-on: ubuntu-latest
    needs: jest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: Yarn install
        run: yarn install

      - name: Run Storybook Build
        run: yarn build:storybook

      - name: Upload test coverage artifact
        uses: actions/upload-artifact@v2
        with:
          name: storybook
          path: storybook
